language: node_js

node_js:
  - "16"
  - "18"
  - "20"

cache:
  npm: true

install:
  - npm ci

script:
  - npm test
  - npm run lint

jobs:
  include:
    - stage: build
      node_js: "20"
      script:
        - npm run build
