-- Initial durable state for git-ci. IDs are generated by the Go store rather
-- than by SQLite so they remain opaque and independent of database internals.

CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE CHECK (length(trim(slug)) > 0),
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    source_type TEXT NOT NULL CHECK (length(trim(source_type)) > 0),
    canonical_path TEXT,
    repository_url TEXT,
    default_branch TEXT NOT NULL CHECK (length(trim(default_branch)) > 0),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    project_id TEXT,
    action TEXT NOT NULL CHECK (length(trim(action)) > 0),
    actor TEXT,
    resource_type TEXT,
    resource_id TEXT,
    metadata_json TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_events_project_created_at
    ON audit_events (project_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    trigger_type TEXT NOT NULL CHECK (length(trim(trigger_type)) > 0),
    status TEXT NOT NULL CHECK (length(trim(status)) > 0),
    ref TEXT,
    commit_sha TEXT,
    started_at INTEGER,
    finished_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_runs_project_created_at
    ON runs (project_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS jobs (
    id TEXT PRIMARY KEY,
    run_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    status TEXT NOT NULL CHECK (length(trim(status)) > 0),
    runner TEXT,
    position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
    started_at INTEGER,
    finished_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    UNIQUE (run_id, name),
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_jobs_run_position
    ON jobs (run_id, position ASC, id ASC);

CREATE TABLE IF NOT EXISTS steps (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL,
    step_index INTEGER NOT NULL CHECK (step_index >= 0),
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    command TEXT,
    status TEXT NOT NULL CHECK (length(trim(status)) > 0),
    started_at INTEGER,
    finished_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at),
    UNIQUE (job_id, step_index),
    FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_steps_job_step_index
    ON steps (job_id, step_index ASC);

CREATE TABLE IF NOT EXISTS deliveries (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    run_id TEXT,
    kind TEXT NOT NULL CHECK (length(trim(kind)) > 0),
    destination TEXT NOT NULL CHECK (length(trim(destination)) > 0),
    status TEXT NOT NULL CHECK (length(trim(status)) > 0),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    request_payload TEXT,
    response_status INTEGER,
    last_error TEXT,
    delivered_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_deliveries_project_created_at
    ON deliveries (project_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS schedules (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    expression TEXT NOT NULL CHECK (length(trim(expression)) > 0),
    branch TEXT,
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    next_run_at INTEGER,
    last_run_at INTEGER,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_schedules_next_run_at
    ON schedules (active, next_run_at ASC);

-- This table deliberately stores only metadata and an external reference.
-- Secret material must never be persisted in this database.
CREATE TABLE IF NOT EXISTS secrets (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    name TEXT NOT NULL CHECK (length(trim(name)) > 0),
    provider TEXT,
    key_reference TEXT,
    version TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    UNIQUE (project_id, name),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_secrets_project_name
    ON secrets (project_id, name ASC);
